# Generated by Django 2.2.13 on 2020-06-22 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='シリーズ名')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolType', models.CharField(max_length=5, verbose_name='記号種類')),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='モンスター名')),
                ('jyaku_hi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jyaku_hi', to='MonHan.Symbol', verbose_name='弱点属性_火')),
                ('jyaku_mizu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jyaku_mizu', to='MonHan.Symbol', verbose_name='弱点属性_水')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MonHan.Series', verbose_name='シリーズ')),
            ],
        ),
    ]
