# Generated by Django 2.2.13 on 2020-06-22 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonHan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='ijyo_bakuha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ijyo_bakuha', to='MonHan.Symbol', verbose_name='状態異常耐性_爆破'),
        ),
        migrations.AddField(
            model_name='monster',
            name='ijyo_doku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ijyo_doku', to='MonHan.Symbol', verbose_name='状態異常耐性_毒'),
        ),
        migrations.AddField(
            model_name='monster',
            name='ijyo_kizetsu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ijyo_kizetsu', to='MonHan.Symbol', verbose_name='状態異常耐性_気絶'),
        ),
        migrations.AddField(
            model_name='monster',
            name='ijyo_mahi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ijyo_mahi', to='MonHan.Symbol', verbose_name='状態異常耐性_麻痺'),
        ),
        migrations.AddField(
            model_name='monster',
            name='ijyo_meki',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ijyo_meki', to='MonHan.Symbol', verbose_name='状態異常耐性_滅気'),
        ),
        migrations.AddField(
            model_name='monster',
            name='ijyo_nori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ijyo_nori', to='MonHan.Symbol', verbose_name='状態異常耐性_乗り'),
        ),
        migrations.AddField(
            model_name='monster',
            name='ijyo_suimin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ijyo_suimin', to='MonHan.Symbol', verbose_name='状態異常耐性_睡眠'),
        ),
        migrations.AddField(
            model_name='monster',
            name='item_koyashi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_koyashi', to='MonHan.Symbol', verbose_name='アイテム耐性_こやし玉'),
        ),
        migrations.AddField(
            model_name='monster',
            name='item_otobaku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_otobaku', to='MonHan.Symbol', verbose_name='アイテム耐性_音爆'),
        ),
        migrations.AddField(
            model_name='monster',
            name='item_otoshi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_otoshi', to='MonHan.Symbol', verbose_name='アイテム耐性_落し穴'),
        ),
        migrations.AddField(
            model_name='monster',
            name='item_senko',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_senko', to='MonHan.Symbol', verbose_name='アイテム耐性_閃光'),
        ),
        migrations.AddField(
            model_name='monster',
            name='item_shibire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_shibire', to='MonHan.Symbol', verbose_name='アイテム耐性_シビレ罠'),
        ),
        migrations.AddField(
            model_name='monster',
            name='item_tsuta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_tsuta', to='MonHan.Symbol', verbose_name='アイテム耐性_ツタ'),
        ),
        migrations.AddField(
            model_name='monster',
            name='item_wananiku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_wananiku', to='MonHan.Symbol', verbose_name='アイテム耐性_罠肉'),
        ),
        migrations.AddField(
            model_name='monster',
            name='jyaku_kami',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jyaku_kami', to='MonHan.Symbol', verbose_name='弱点属性_雷'),
        ),
        migrations.AddField(
            model_name='monster',
            name='jyaku_kori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jyaku_kori', to='MonHan.Symbol', verbose_name='弱点属性_氷'),
        ),
        migrations.AddField(
            model_name='monster',
            name='jyaku_ryu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jyaku_ryu', to='MonHan.Symbol', verbose_name='弱点属性_龍'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='jyaku_hi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jyaku_hi', to='MonHan.Symbol', verbose_name='弱点属性_火'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='jyaku_mizu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jyaku_mizu', to='MonHan.Symbol', verbose_name='弱点属性_水'),
        ),
    ]
