# Generated by Django 2.2.13 on 2020-06-24 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MonHan', '0002_auto_20200622_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuatsu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, verbose_name='風圧名')),
            ],
        ),
        migrations.CreateModel(
            name='JyotaiIjyo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='状態異常名')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, verbose_name='種族名')),
            ],
        ),
        migrations.CreateModel(
            name='Roar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, verbose_name='咆哮名')),
            ],
        ),
        migrations.CreateModel(
            name='Vibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, verbose_name='震動名')),
            ],
        ),
        migrations.CreateModel(
            name='Yarare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='やられ名')),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='erce',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MonHan.Race', verbose_name='種族'),
        ),
        migrations.AddField(
            model_name='monster',
            name='fuatsu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MonHan.Fuatsu', verbose_name='風圧'),
        ),
        migrations.AddField(
            model_name='monster',
            name='jyotaiijyo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MonHan.JyotaiIjyo', verbose_name='状態異常'),
        ),
        migrations.AddField(
            model_name='monster',
            name='roar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MonHan.Roar', verbose_name='咆哮'),
        ),
        migrations.AddField(
            model_name='monster',
            name='vibration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MonHan.Vibration', verbose_name='震動'),
        ),
        migrations.AddField(
            model_name='monster',
            name='yarare',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MonHan.Yarare', verbose_name='やられ'),
        ),
    ]
