# Generated by Django 2.2.13 on 2020-07-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonHan', '0003_auto_20200625_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuatsu',
            options={'verbose_name': '風圧', 'verbose_name_plural': '風圧'},
        ),
        migrations.AlterModelOptions(
            name='jyotaiijyo',
            options={'verbose_name': '状態異常', 'verbose_name_plural': '状態異常'},
        ),
        migrations.AlterModelOptions(
            name='monster',
            options={'verbose_name': 'モンスター', 'verbose_name_plural': 'モンスター'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'シリーズ名', 'verbose_name_plural': 'シリーズ名'},
        ),
        migrations.AlterModelOptions(
            name='symbol',
            options={'verbose_name': '記号種類', 'verbose_name_plural': '記号種類'},
        ),
        migrations.AlterModelOptions(
            name='vibration',
            options={'verbose_name': '震動', 'verbose_name_plural': '震動'},
        ),
        migrations.AlterModelOptions(
            name='yarare',
            options={'verbose_name': 'やられ', 'verbose_name_plural': 'やられ'},
        ),
        migrations.RemoveField(
            model_name='monster',
            name='erce',
        ),
        migrations.AddField(
            model_name='monster',
            name='race',
            field=models.IntegerField(choices=[(1, '鳥竜種'), (2, '牙竜種'), (3, '魚竜種'), (4, '遺存種'), (5, '飛竜種'), (6, '古龍種'), (7, '獣竜種')], null=True, verbose_name='種族'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='roar',
            field=models.IntegerField(choices=[(1, '大'), (2, '小'), (3, 'なし')], null=True, verbose_name='咆哮'),
        ),
        migrations.DeleteModel(
            name='Race',
        ),
        migrations.DeleteModel(
            name='Roar',
        ),
    ]
