# Generated by Django 2.2.13 on 2020-07-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonHan', '0005_auto_20200703_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='fuatsu',
            field=models.IntegerField(blank=True, choices=[(1, '大'), (2, '小'), (3, 'なし')], null=True, verbose_name='風圧'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='ijyo_bakuha',
            field=models.IntegerField(blank=True, choices=[(1, '◎'), (2, '〇'), (3, '△'), (4, '×'), (5, '？')], null=True, verbose_name='状態異常耐性_爆破'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='ijyo_doku',
            field=models.IntegerField(blank=True, choices=[(1, '◎'), (2, '〇'), (3, '△'), (4, '×'), (5, '？')], null=True, verbose_name='状態異常耐性_毒'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='ijyo_kizetsu',
            field=models.IntegerField(blank=True, choices=[(1, '◎'), (2, '〇'), (3, '△'), (4, '×'), (5, '？')], null=True, verbose_name='状態異常耐性_気絶'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='ijyo_mahi',
            field=models.IntegerField(blank=True, choices=[(1, '◎'), (2, '〇'), (3, '△'), (4, '×'), (5, '？')], null=True, verbose_name='状態異常耐性_麻痺'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='ijyo_meki',
            field=models.IntegerField(blank=True, choices=[(1, '◎'), (2, '〇'), (3, '△'), (4, '×'), (5, '？')], null=True, verbose_name='状態異常耐性_滅気'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='ijyo_nori',
            field=models.IntegerField(blank=True, choices=[(1, '◎'), (2, '〇'), (3, '△'), (4, '×'), (5, '？')], null=True, verbose_name='状態異常耐性_乗り'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='ijyo_suimin',
            field=models.IntegerField(blank=True, choices=[(1, '◎'), (2, '〇'), (3, '△'), (4, '×'), (5, '？')], null=True, verbose_name='状態異常耐性_睡眠'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='item_koyashi',
            field=models.IntegerField(blank=True, choices=[(1, '◎'), (2, '〇'), (3, '△'), (4, '×'), (5, '？')], null=True, verbose_name='アイテム耐性_こやし玉'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='item_otobaku',
            field=models.IntegerField(blank=True, choices=[(1, '◎'), (2, '〇'), (3, '△'), (4, '×'), (5, '？')], null=True, verbose_name='アイテム耐性_音爆'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='item_otoshi',
            field=models.IntegerField(blank=True, choices=[(1, '◎'), (2, '〇'), (3, '△'), (4, '×'), (5, '？')], null=True, verbose_name='アイテム耐性_落し穴'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='item_senko',
            field=models.IntegerField(blank=True, choices=[(1, '◎'), (2, '〇'), (3, '△'), (4, '×'), (5, '？')], null=True, verbose_name='アイテム耐性_閃光'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='item_shibire',
            field=models.IntegerField(blank=True, choices=[(1, '◎'), (2, '〇'), (3, '△'), (4, '×'), (5, '？')], null=True, verbose_name='アイテム耐性_シビレ罠'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='item_tsuta',
            field=models.IntegerField(blank=True, choices=[(1, '◎'), (2, '〇'), (3, '△'), (4, '×'), (5, '？')], null=True, verbose_name='アイテム耐性_ツタ'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='item_wananiku',
            field=models.IntegerField(blank=True, choices=[(1, '◎'), (2, '〇'), (3, '△'), (4, '×'), (5, '？')], null=True, verbose_name='アイテム耐性_罠肉'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='jyaku_hi',
            field=models.IntegerField(blank=True, choices=[(1, '◎'), (2, '〇'), (3, '△'), (4, '×'), (5, '？')], null=True, verbose_name='弱点属性_火'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='jyaku_kami',
            field=models.IntegerField(blank=True, choices=[(1, '◎'), (2, '〇'), (3, '△'), (4, '×'), (5, '？')], null=True, verbose_name='弱点属性_雷'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='jyaku_kori',
            field=models.IntegerField(blank=True, choices=[(1, '◎'), (2, '〇'), (3, '△'), (4, '×'), (5, '？')], null=True, verbose_name='弱点属性_氷'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='jyaku_mizu',
            field=models.IntegerField(blank=True, choices=[(1, '◎'), (2, '〇'), (3, '△'), (4, '×'), (5, '？')], null=True, verbose_name='弱点属性_水'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='jyaku_ryu',
            field=models.IntegerField(blank=True, choices=[(1, '◎'), (2, '〇'), (3, '△'), (4, '×'), (5, '？')], null=True, verbose_name='弱点属性_龍'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='jyotaiijyo',
            field=models.IntegerField(blank=True, choices=[(1, '毒'), (2, '猛毒'), (3, '麻痺'), (4, '睡眠'), (5, '裂傷'), (6, '爆破'), (7, '気絶'), (8, '防御力DOWN'), (9, '瘴気浸食状態'), (10, 'なし')], null=True, verbose_name='状態異常'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='race',
            field=models.IntegerField(blank=True, choices=[(1, '鳥竜種'), (2, '牙竜種'), (3, '魚竜種'), (4, '遺存種'), (5, '飛竜種'), (6, '古龍種'), (7, '獣竜種')], null=True, verbose_name='種族'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='roar',
            field=models.IntegerField(blank=True, choices=[(1, '大'), (2, '小'), (3, 'なし')], null=True, verbose_name='咆哮'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='series',
            field=models.IntegerField(blank=True, choices=[(1, 'IB'), (2, 'MHW')], null=True, verbose_name='シリーズ'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='vibration',
            field=models.IntegerField(blank=True, choices=[(1, '大'), (2, '小'), (3, 'なし')], null=True, verbose_name='震動'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='yarare',
            field=models.IntegerField(blank=True, choices=[(1, '火'), (2, '水'), (3, '雷'), (4, '氷'), (5, '龍'), (6, 'なし')], null=True, verbose_name='やられ'),
        ),
    ]
