# Generated by Django 2.2.15 on 2020-09-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonHan', '0006_auto_20200703_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='fuatsu',
        ),
        migrations.RemoveField(
            model_name='monster',
            name='yarare',
        ),
        migrations.AlterField(
            model_name='monster',
            name='jyotaiijyo',
            field=models.IntegerField(blank=True, choices=[(1, '毒'), (2, '猛毒'), (3, '麻痺'), (4, '睡眠'), (5, '裂傷'), (6, '爆破'), (7, '気絶'), (8, '防御力DOWN'), (9, '瘴気浸食状態'), (10, '泥'), (11, '凍結やられ'), (12, '火'), (13, 'なし')], null=True, verbose_name='状態異常'),
        ),
    ]
