# Generated by Django 2.2.15 on 2020-09-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MonHan', '0007_auto_20200913_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='fuatsu1',
            field=models.IntegerField(blank=True, choices=[(1, '火'), (2, '水'), (3, '雷'), (4, '氷'), (5, '龍'), (6, 'なし')], null=True, verbose_name='風圧１'),
        ),
        migrations.AddField(
            model_name='monster',
            name='fuatsu2',
            field=models.IntegerField(blank=True, choices=[(1, '大'), (2, '小'), (3, 'なし')], null=True, verbose_name='風圧２'),
        ),
        migrations.AddField(
            model_name='monster',
            name='yarare1',
            field=models.IntegerField(blank=True, choices=[(1, '火'), (2, '水'), (3, '雷'), (4, '氷'), (5, '龍'), (6, 'なし')], null=True, verbose_name='やられ１'),
        ),
        migrations.AddField(
            model_name='monster',
            name='yarare2',
            field=models.IntegerField(blank=True, choices=[(1, '火'), (2, '水'), (3, '雷'), (4, '氷'), (5, '龍'), (6, 'なし')], null=True, verbose_name='やられ２'),
        ),
    ]
