# Generated by Django 2.2.15 on 2020-08-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='create_dt',
            new_name='created_at',
        ),
    ]
